# ===============================
# DATABASE CONFIGURATION
# ===============================
database:
  # HOST CONNECTION DETAILS
  enabled: true
  host: localhost
  port: 3306
  database: my_database
  username: my_username
  password: my_password

  # =============================
  # ADVANCED DATABASE SETTINGS
  # =============================
  # MySQL Register Reloaded uses HikariCP for database connections.
  # More information about the settings can be found here:
  # https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#frequently-used
  advanced:
    useSSL: false
    poolSize: 10
    timeout: 30000